# Generated by Django 3.1.3 on 2020-12-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='ppic'),
        ),
    ]
