# Generated by Django 3.1.3 on 2020-12-27 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20201227_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('link', models.URLField(blank=True, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prof', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='home.post')),
            ],
        ),
        migrations.CreateModel(
            name='follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followersusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL)),
                ('followingusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to=settings.AUTH_USER_MODEL)),
                ('mainuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
