# Generated by Django 3.1.3 on 2020-12-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201227_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='home.post'),
        ),
    ]
