# Generated by Django 3.1.3 on 2021-01-03 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_auto_20210103_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='followersusers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows',
            name='followingusers',
            field=models.ManyToManyField(blank=True, related_name='user_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
