# Generated by Django 3.1.3 on 2020-12-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20201227_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved',
        ),
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
