# Generated by Django 3.1.3 on 2021-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210102_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='gallery/default.jpg', upload_to='gallery'),
        ),
    ]
