# Generated by Django 3.1.3 on 2021-01-03 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_auto_20210103_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followersusers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followersusers',
            field=models.ManyToManyField(blank=True, related_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followingusers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followingusers',
            field=models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
