# Generated by Django 3.1.3 on 2021-01-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_notifications_triggeredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='triggeredby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentnotf', to='home.profile'),
        ),
    ]
