# Generated by Django 3.1.3 on 2021-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210105_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followercount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='followingcount',
            field=models.IntegerField(default=0),
        ),
    ]
