# Generated by Django 3.1.3 on 2021-01-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201227_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
    ]
